events {}

http {

  # Redirige vers la console web MinIO
  server {
    listen 80;
    server_name localhost;

    location / {
      proxy_pass http://minio:9001;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
  }

  # Redirige vers l'API S3 MinIO
  server {
    listen 9000;
    server_name localhost;

    location / {
      proxy_pass http://minio:9000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

}